# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add environment variables to ..env
        run: |
          echo ADMINS=${{ secrets.ADMINS }} >> .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo ip=${{ secrets.ip }} >> .env
   
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir bot || true
            
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "bot"
          
      - name: run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/bot
            sudo docker-compose -f docker-compose.yml up --build -d 
            sudo docker rmi $(sudo docker images -f dangling=true -q)|| true
            
      - name: run docker sock
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker run -d /var/run/docker.sock:/var/run/docker.sock ubuntu /bin/bash
              
